name: Publish nuget

on:
    push:
        tags:
            - 'v*'
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                dotnet-version: '8.x'

            - name: List files
              run: ls -la

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.x'

            - name: Restore dependencies
              run: dotnet restore Akasha.Contracts.csproj

            - name: Build
              run: dotnet build Akasha.Contracts.csproj -c Release --no-restore

            - name: Pack
              run: dotnet pack Akasha.Contracts.csproj -c Release --no-build -o ./nupkg

            - name: Push package
              run: |
                dotnet nuget push ./nupkg/*.nupkg \
                --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json \
                --api-key ${{secrets.GITHUB_TOKEN}}